/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppProjects {
        "match": MatchResults;
    }
    interface AppRoot {
        "url": String;
    }
    interface AppStart {
    }
}
declare global {
    interface HTMLAppProjectsElement extends Components.AppProjects, HTMLStencilElement {
    }
    var HTMLAppProjectsElement: {
        prototype: HTMLAppProjectsElement;
        new (): HTMLAppProjectsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppStartElement extends Components.AppStart, HTMLStencilElement {
    }
    var HTMLAppStartElement: {
        prototype: HTMLAppStartElement;
        new (): HTMLAppStartElement;
    };
    interface HTMLElementTagNameMap {
        "app-projects": HTMLAppProjectsElement;
        "app-root": HTMLAppRootElement;
        "app-start": HTMLAppStartElement;
    }
}
declare namespace LocalJSX {
    interface AppProjects {
        "match"?: MatchResults;
    }
    interface AppRoot {
        "url"?: String;
    }
    interface AppStart {
    }
    interface IntrinsicElements {
        "app-projects": AppProjects;
        "app-root": AppRoot;
        "app-start": AppStart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-projects": LocalJSX.AppProjects & JSXBase.HTMLAttributes<HTMLAppProjectsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-start": LocalJSX.AppStart & JSXBase.HTMLAttributes<HTMLAppStartElement>;
        }
    }
}
